const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function fixture(){
 const queue=[],replies=[],writes=[],calls=[],objects={};let next=1000;
 function object(id,values={}){const o={id,...values,get(k){const v=this[k];return Array.isArray(v)?v:[v];},set(k,v){writes.push([id,k,v]);if(this.failSet===k)throw Error('write failure');if(/routing_/.test(k)&&typeof v==='string')v=JSON.parse(v);this[k]=v;},call(op,...args){calls.push([id,op,...args]);if(op==='str_for_value')return String(args[0]);throw Error('Unsupported mock call '+op);}};objects[id]=o;return o;}
 function param(id,value,extra={}){return object(id,{type:'DeviceParameter',name:'p'+id,value,min:0,max:1,is_quantized:0,is_enabled:1,automation_state:0,...extra});}
 const song=object(1,{tracks:[10,11],return_tracks:[20],master_track:[2],scenes:[70,71],cue_points:[80],is_playing:0,record_mode:0,session_record:0,current_song_time:12});
 for(const id of [2,10,11,20]){object(id,{name:'Track'+id,color_index:3,is_frozen:0,is_foldable:0,group_track:[],mute:0,solo:0,devices:[],arrangement_clips:[],clip_slots:[],mixer_device:[id*10]});object(id*10,{volume:[id*10+1],panning:[id*10+2],sends:id===2?[]:[id*10+3]});param(id*10+1,0.7);param(id*10+2,0,{min:-1});if(id!==2)param(id*10+3,0);}
 // Return mixer id 200 does not overlap tracks; master mixer id 20 does, so give master a separate mixer.
 object(20,{name:'Return',is_frozen:0,is_foldable:0,group_track:[],mute:0,solo:0,devices:[],arrangement_clips:[],clip_slots:[],mixer_device:[200]});
 objects[2].mixer_device=[900];object(900,{volume:[901],panning:[902],sends:[]});param(901,0.7);param(902,0,{min:-1});
 const clip=object(50,{name:'Clip',color_index:4,is_midi_clip:1,loop_start:0,loop_end:4,start_marker:0,end_marker:4,looping:1,muted:0,notes:[{note_id:1,pitch:60,start_time:0,duration:1,velocity:100,mute:0,probability:1},{note_id:2,pitch:62,start_time:2,duration:1,velocity:90,mute:0,probability:1}]});objects[10].arrangement_clips=[50];
 clip.call=function(op,payload){calls.push([50,op,payload]);const doc=JSON.parse(payload);if(op==='apply_note_modifications'){for(const n of doc.notes)this.notes[this.notes.findIndex(v=>v.note_id===n.note_id)]={...n};}else if(op==='add_new_notes')this.notes.push(...doc.notes.map(n=>({note_id:next++,...n})));else if(op==='remove_notes_by_id')this.notes=this.notes.filter(n=>!doc.note_ids.includes(n.note_id));else throw Error(op);};
 object(70,{name:'A',color_index:1,clip_slots:[]});object(71,{name:'B',color_index:2,clip_slots:[]});object(80,{name:'Verse',time:4});
 song.call=function(op,index){calls.push([1,op,index]);if(op==='duplicate_track'){const src=objects[this.tracks[index]],id=next++;object(id,{...src,id,group_track:[...src.group_track]});this.tracks.splice(index+1,0,id);}else if(op==='delete_track')this.tracks.splice(index,1);else if(op==='delete_return_track')this.return_tracks.splice(index,1);else if(op==='create_scene'||op==='duplicate_scene'){const id=next++;object(id,{name:'New',color_index:0,clip_slots:[]});this.scenes.splice(op==='create_scene'?this.scenes.length:index+1,0,id);}else if(op==='delete_scene')this.scenes.splice(index,1);else if(op==='set_or_delete_cue'){const found=this.cue_points.find(id=>objects[id].time===this.current_song_time);if(found)this.cue_points=this.cue_points.filter(id=>id!==found);else{const id=next++;object(id,{name:'New',time:this.current_song_time});this.cue_points.push(id);this.cue_points.sort((a,b)=>objects[a].time-objects[b].time);}}else throw Error(op);};
 const ctx=vm.createContext({Task:function(fn){this.schedule=()=>queue.push(fn);}});
 for(const file of ['live-api.js','live-production.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',file),'utf8'),ctx);
 Object.assign(ctx,{SESSION:'s',api:()=>song,byId:id=>{if(!objects[id])throw Error('Missing object');return objects[id];},track:id=>{if(![...song.tracks,...song.return_tracks,2].includes(id))throw Error('Outside Set');return objects[id];},host:()=>objects[2],val:(o,k)=>o[k],ids:(o,k)=>(o[k]||[]).slice(),clipTrack:id=>{if(id!==50)throw Error('Outside Set');return objects[10];},checkClip:id=>{if(id!==50)throw Error('Outside Set');return clip;},notes:c=>structuredClone(c.notes),devicesIn:t=>(t.devices||[]).map(id=>({id,parentId:t.id,name:objects[id].name,className:'PluginDevice'})),reply:(id,result,error)=>replies.push({id,result,error})});
 let rid=0;
 function run(op,args={},id){ctx.raw=JSON.stringify({id:id||String(++rid),op,expectedSession:'s',...args});vm.runInContext('extendedDispatch(JSON.parse(raw))',ctx);}
 function read(fn,...args){ctx.jsonArgs=JSON.stringify(args);return JSON.parse(vm.runInContext('JSON.stringify('+fn+'.apply(null,JSON.parse(jsonArgs)))',ctx));}
 return {ctx,objects,song,clip,queue,writes,calls,replies,param,object,run,read,flush(){while(queue.length)queue.shift()();},last(){return replies.at(-1);}};
}
test('batch preflights all changes and resolves sends by Return ID',()=>{const f=fixture();f.run('x_batch',{changes:[{trackId:10,property:'volume',value:0.4,expectedValue:0.7},{trackId:11,property:'send',returnTrackId:20,value:0.2,expectedValue:0},{trackId:10,property:'name',value:'Guitar',expectedValue:'Track10'}]});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.objects[113].value,0.2);assert.equal(f.objects[10].name,'Guitar');
 const bad=fixture();bad.run('x_batch',{changes:[{trackId:10,property:'volume',value:0.4,expectedValue:0.7},{trackId:11,property:'send',returnTrackId:999,value:0.2,expectedValue:0}]});assert.match(bad.last().error,/Return/);assert.equal(bad.writes.length,0);});
test('batch rejects duplicate targets, automation, stale values/session and recording',()=>{for(const modify of [f=>f.objects[101].automation_state=1,f=>f.objects[101].is_enabled=0,f=>f.objects[10].is_frozen=1,f=>f.song.is_playing=1,f=>f.song.record_mode=1,f=>f.song.session_record=1,f=>f.ctx.SESSION='old']){const f=fixture();modify(f);f.run('x_batch',{changes:[{trackId:10,property:'volume',value:0.2,expectedValue:0.7}]});assert(f.last().error);assert.equal(f.writes.length,0);}
 const f=fixture(),ch={trackId:10,property:'volume',value:0.2,expectedValue:0.7};f.run('x_batch',{changes:[ch,ch]});assert.match(f.last().error,/Duplicate/);assert.equal(f.writes.length,0);});
test('batch reports partial writes and does not repeat cached request',()=>{const f=fixture();f.objects[113].failSet='value';const a={changes:[{trackId:10,property:'volume',value:0.2,expectedValue:0.7},{trackId:11,property:'send',returnTrackId:20,value:0.4,expectedValue:0}]};f.run('x_batch',a,'same');assert.match(f.last().error,/completed writes/);const count=f.writes.length;f.run('x_batch',a,'same');assert.equal(f.writes.length,count);});
test('routing uses available identifier dictionaries and read-back',()=>{const f=fixture(),t=f.objects[10];for(const k of ['input_routing_type','input_routing_channel','output_routing_type','output_routing_channel']){t[k]={identifier:'a',display_name:'A'};t['available_'+k+'s']={['available_'+k+'s']:[t[k],{identifier:'b',display_name:'B'}]};}f.run('x_routing_set',{trackId:10,property:'output_routing_type',identifier:'b',expectedIdentifier:'a'});f.flush();assert.equal(f.last().result.after.routes.output_routing_type.current.identifier,'b');const n=f.writes.length;f.run('x_routing_set',{trackId:10,property:'output_routing_type',identifier:'missing',expectedIdentifier:'b'});assert(f.last().error);assert.equal(f.writes.length,n);});
test('normal track duplicate/delete and Return delete preserve order',()=>{for(const [op,id] of [['x_track_duplicate',10],['x_track_delete',10],['x_track_delete',20]]){const f=fixture();f.run(op,{trackId:id,expectedName:f.objects[id].name,expectedTrackIds:[10,11],expectedReturnTrackIds:[20]});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.song.tracks.length,op==='x_track_duplicate'?3:id===10?1:2);}});
test('track operations protect host/group/last track and stale topology',()=>{for(const setup of [f=>f.ctx.host=()=>f.objects[10],f=>f.objects[10].is_foldable=1,f=>f.song.tracks.reverse()]){const f=fixture();setup(f);f.run('x_track_delete',{trackId:10,expectedName:'Track10',expectedTrackIds:[10,11],expectedReturnTrackIds:[20]});assert(f.last().error);assert.equal(f.calls.length,0);}});
test('MIDI updates velocity timing duration and preserves note IDs/unmodified values',()=>{const f=fixture();f.run('x_notes_update',{clipId:50,expectedFingerprint:f.ctx.fingerprint(f.clip.notes),changes:[{noteId:1,velocity:70,start_time:0.125,duration:0.5}]});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.clip.notes[0].note_id,1);assert.equal(f.clip.notes[0].velocity,70);assert.equal(f.clip.notes[1].velocity,90);});
test('MIDI additions and deletion preserve other notes and verify identities',()=>{for(const op of ['x_notes_add','x_notes_delete']){const f=fixture();f.run(op,{clipId:50,expectedFingerprint:f.ctx.fingerprint(f.clip.notes),...(op==='x_notes_add'?{notes:[{pitch:64,start_time:1,duration:0.5,velocity:80}]}:{noteIds:[1]})});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.clip.notes.length,op==='x_notes_add'?3:1);assert(f.clip.notes.some(n=>n.note_id===2));}});
test('MIDI rejects collisions, missing IDs and stale fingerprints before any mutation',()=>{for(const args of [{expectedFingerprint:'wrong',changes:[{noteId:1,velocity:80}]},{changes:[{noteId:999,velocity:80}]},{changes:[{noteId:1,pitch:62,start_time:2}]},{changes:[{noteId:1,duration:0}]}]){const f=fixture();f.run('x_notes_update',{clipId:50,expectedFingerprint:f.ctx.fingerprint(f.clip.notes),...args});assert(f.last().error);assert.equal(f.calls.length,0);}});
test('clip name/color and loop ranges set in valid order; detects concurrent edits',()=>{const f=fixture(),before=f.read('xClip',50);f.run('x_clip_set',{clipId:50,expectedFingerprint:before.fingerprint,settings:{name:'8 bars',colorIndex:8,loopStart:8,loopEnd:16}});f.flush();assert.equal(f.last().result.verified,true);assert.deepEqual(f.writes.slice(0,2).map(w=>w[1]),['loop_end','loop_start']);const g=fixture();g.run('x_clip_set',{clipId:50,expectedFingerprint:g.read('xClip',50).fingerprint,settings:{name:'new'}});g.clip.muted=1;g.flush();assert.match(g.last().error,/read-back/);});
test('scene create/duplicate/delete/update check list identities and never launch',()=>{for(const action of ['create','duplicate','delete','update']){const f=fixture();f.run('x_scene',{expectedFingerprint:f.read('xScenes').fingerprint,action,...(action==='create'?{name:'Chorus'}:{sceneId:70,...(action==='update'?{name:'Verse',colorIndex:8}:{})})});f.flush();assert.equal(f.last().result.verified,true);assert(!f.calls.some(c=>c[1]==='fire'));}});
test('locator create/rename/delete restore playhead and retain other locators',()=>{for(const action of ['create','rename','delete']){const f=fixture();f.run('x_locator',{expectedFingerprint:f.read('xLocators').fingerprint,action,...(action==='create'?{name:'Chorus',beat:16}:{locatorId:80,...(action==='rename'?{name:'Intro'}:{})})});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.song.current_song_time,12);}});
test('locator create never toggles occupied position and fails if playhead moves',()=>{const f=fixture();f.run('x_locator',{expectedFingerprint:f.read('xLocators').fingerprint,action:'create',beat:4,name:'No'});assert.match(f.last().error,/already exists/);assert.equal(f.calls.length,0);const g=fixture();g.run('x_locator',{expectedFingerprint:g.read('xLocators').fingerprint,action:'create',beat:16,name:'New'});g.song.current_song_time=20;g.flush();assert.equal(g.calls.length,0);assert.equal(g.song.current_song_time,20);assert(g.last().error);});
test('mix captures plugin parameters and guards topology and automated restore',()=>{const f=fixture();f.object(300,{name:'Space Delay',parameters:[301]});f.param(301,0.5);f.objects[10].devices=[300];const state=f.read('xMix',[10]);assert(state.tracks[0].parameters.some(p=>p.id===301));f.run('x_mix_restore',{trackIds:[10],expectedFingerprint:state.fingerprint,expectedTopologyFingerprint:state.topologyFingerprint,values:[{id:301,property:'value',value:0.2},{id:10,property:'mute',value:1}]});f.flush();assert.equal(f.last().result.verified,true);assert.equal(f.objects[301].value,0.2);
 f.objects[301].automation_state=1;const now=f.read('xMix',[10]),n=f.writes.length;f.run('x_mix_restore',{trackIds:[10],expectedFingerprint:now.fingerprint,expectedTopologyFingerprint:now.topologyFingerprint,values:[{id:301,property:'value',value:0.8}]});assert(f.last().error);assert.equal(f.writes.length,n);});
module.exports={fixture};
