const id={type:'string',minLength:1,maxLength:128},beat={type:'number',minimum:0,maximum:1576800};
const common={targetId:id,clipId:id,parameterId:id};
const range={...common,startBeat:beat,endBeat:beat,sampleCount:{type:'integer',minimum:2,maximum:256}};
const guard={readToken:id,expectedSession:id};
const unit={type:'number',minimum:0,maximum:1};
const tools=[
 ['live_generate_automation_curve','Generate sampled cubic Bezier points offline using normalized control handles. No Live changes. Returns beat/value points plus time/value points for saved-Set editing; choose values in the destination native units. This is a polyline approximation, not native Live Bezier handles.','automation_curve',{startBeat:beat,endBeat:beat,startValue:{type:'number'},endValue:{type:'number'},x1:unit,y1:unit,x2:unit,y2:unit,sampleCount:{type:'integer',minimum:2,maximum:128}},['startBeat','endBeat','startValue','endValue','x1','y1','x2','y2','sampleCount'],true],
 ['live_prepare_automation_recording','Prepare a bounded real-time Arrangement parameter recording, including master song_tempo. Does not start playback. Remote IDs, native API values. All tracks disarmed, Arrangement active, loop/punch/count-in/Link off. Existing automation requires overwriteAutomation=1 and a saved backup. Linear interpolation, at most 64 beats/120 seconds; scheduler timing is approximate.','automation_record_prepare',{targetId:id,parameterId:id,points:{type:'array',minItems:2,maxItems:128,items:{type:'object',properties:{beat,value:{type:'number'}},required:['beat','value'],additionalProperties:false}},maxSeconds:{type:'number',minimum:1,maximum:120},overwriteAutomation:{type:'integer',minimum:0,maximum:1}},['targetId','parameterId','points','maxSeconds','overwriteAutomation'],true],
 ['live_start_automation_recording','Start a prepared Arrangement recording (plan expires in 60 seconds). Starts playback and records parameter gestures, stops automatically at end or wall-clock limit. Poll status. Can overwrite automation; exact points are not guaranteed or read back. Inspect failures; never blindly restart.','automation_record_start',{prepareToken:id,expectedSession:id},['prepareToken','expectedSession'],false],
 ['live_automation_recording_status','Read recording progress and cleanup outcome. completed means the transport run finished, not exact curve verification. Read saved Set events for durable verification.','automation_record_status',{operationId:id,expectedSession:id},['operationId','expectedSession'],true],
 ['live_stop_automation_recording','Cancel an active recording and stop playback/recording, close the gesture and restore automation arm/playhead. Partial automation remains; this is not undo.','automation_record_stop',{operationId:id,expectedSession:id},['operationId','expectedSession'],false],
 ['live_automation_capabilities','Read the running Live automation API capabilities. Does not create envelopes or change transport. Reports actual runtime method availability; availability alone is not operation verification.','automation_capabilities',{},[],true],
 ['live_automation_targets','Discover Remote Script clip and parameter IDs (not Max IDs), capabilities and ranges on one remote targetId from live_browser_status. Session clips only for writes; native parameter units.','automation_targets',{targetId:id},['targetId'],true],
 ['live_read_automation','Sample a Session clip envelope at evenly spaced beats. Samples are NOT original breakpoints or an exact backup. Returns a short-lived readToken required for editing. Does not create an envelope.','automation_read',range,Object.keys(range),true],
 ['live_write_automation','Write bounded steps or an approximated linear ramp in a Session clip using a fresh readToken. Requires stopped playback/recording. Existing curve outside the range is not intentionally cleared; Live may change boundary interpolation. Linear is sampled steps, not native Bezier. Partial failures must be inspected, never retried blindly.','automation_write',{...guard,points:{type:'array',minItems:2,maxItems:128,items:{type:'object',properties:{beat,value:{type:'number'}},required:['beat','value'],additionalProperties:false}},shape:{type:'string',enum:['step','linear']},resolution:{type:'integer',minimum:1,maximum:256}},['readToken','expectedSession','points','shape','resolution'],false],
 ['live_clear_automation','Destructively remove the ENTIRE selected Session clip parameter envelope, not just the sampled range. Other parameter envelopes are preserved. Requires a fresh readToken; samples are not an exact restorable backup.','automation_clear',guard,Object.keys(guard),false]
];
function generateCurve(a){
 for(const k of ['startBeat','endBeat','startValue','endValue','x1','y1','x2','y2'])if(!Number.isFinite(a[k]))throw Error('Finite curve coordinates required');
 if(!(0<=a.startBeat&&a.startBeat<a.endBeat&&a.endBeat<=1576800))throw Error('Increasing beat range required');
 if(['x1','y1','x2','y2'].some(k=>a[k]<0||a[k]>1)||a.x1>a.x2)throw Error('Ordered x handles and all handles in 0..1 required');
 if(!Number.isInteger(a.sampleCount)||a.sampleCount<2||a.sampleCount>128)throw Error('Use 2..128 samples');
 const bez=(t,c1,c2)=>3*(1-t)*(1-t)*t*c1+3*(1-t)*t*t*c2+t*t*t;
 const points=Array.from({length:a.sampleCount},(_,i)=>{const t=i/(a.sampleCount-1);return {beat:a.startBeat+(a.endBeat-a.startBeat)*bez(t,a.x1,a.x2),value:a.startValue+(a.endValue-a.startValue)*bez(t,a.y1,a.y2)};});
 if(points.some((p,i)=>!Number.isFinite(p.value)||(i&&p.beat<=points[i-1].beat)))throw Error('Curve precision exceeded');
 return {points,setPoints:points.map(p=>({time:p.beat,value:p.value})),approximation:'sampled-cubic-bezier',liveChanged:false,warning:'Native Live handles are not authored. Session writes are steps; real-time recording has scheduler jitter; saved Set values may use different units.'};
}
module.exports={tools,generateCurve};
